services:
  app:
    build: .
    command: bash -c "rails s -b 0.0.0.0"
    env_file:
      - .env
    environment:
      TZ: America/Sao_Paulo
    ports:
      - 3000:3000
    user: 1000:1000
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    working_dir: /app

volumes:
  rubygems:
